# Generated by Django 3.1.2 on 2021-04-19 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('original_name', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], max_length=1)),
                ('background', models.CharField(choices=[('M', 'Military'), ('C', 'Civilian'), ('U', 'Unspecified')], max_length=1)),
                ('year_of_birth', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2010)])),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.country')),
            ],
        ),
    ]
