# Generated by Django 3.2 on 2021-04-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='type_of_launch',
            new_name='launch_type',
        ),
    ]
