# Generated by Django 3.1.2 on 2021-04-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Astronaut',
        ),
    ]
