# Generated by Django 3.2 on 2021-04-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0002_rename_type_of_launch_launch_launch_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronautoccupation',
            old_name='year_of_join',
            new_name='join_year',
        ),
        migrations.AlterUniqueTogether(
            name='astronautoccupation',
            unique_together={('astronaut', 'mission', 'role', 'join_year')},
        ),
    ]
