# Generated by Django 3.1.7 on 2021-04-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0002_stage_engine'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='astronautselection',
            unique_together={('astronaut', 'selection', 'year_of_selection')},
        ),
    ]
