# Generated by Django 3.1.2 on 2021-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0002_delete_astronaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Americas', 'Americas'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Oceania', 'Oceania')], default='Americas', max_length=10),
        ),
    ]
