# Generated by Django 3.1.7 on 2021-04-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0003_auto_20210422_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='astronautoccupation',
            unique_together={('astronaut', 'mission', 'role', 'year_of_join')},
        ),
    ]
