# Generated by Django 3.1.7 on 2021-04-21 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0004_astronaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronautOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40)),
                ('year_of_join', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
            ],
        ),
        migrations.CreateModel(
            name='AstronautSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_selection', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('success_or_fail', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail'), ('unknown', 'unknown')], max_length=20)),
                ('type_of_launch', models.CharField(choices=[('Orbital', 'Orbital'), ('DeepSpaceMission', 'DeepSpaceMission'), ('unknown', 'unknown')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchVehicle',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=256)),
                ('alias', models.CharField(max_length=256)),
                ('min_stage', models.IntegerField()),
                ('max_stage', models.IntegerField()),
                ('launch_mass', models.FloatField()),
                ('TO_thrust', models.FloatField()),
                ('vehicle_class', models.CharField(choices=[('D', 'Extraterrestrial Deep Space Launch'), ('M', 'Missile'), ('O', 'Orbital Vehicle'), ('R', 'Research Rocket'), ('V', 'Reentry Test Vehicle'), ('X', 'Exoatmospheric test'), ('Y', 'Exoatmospheric weather rocket'), ('A', 'Endoatmospheric missile'), ('C', 'Cruise missile'), ('Q', 'Endoatmospheric reentry test vehicle'), ('T', 'Endoatmospheric test/research'), ('W', 'Endoatmospheric Weather rocket')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('diameter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('code', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('U_code', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('english_name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('t_start', models.DateField()),
                ('t_stop', models.DateField()),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.coordinate')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.country')),
                ('parent_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('dry_mass', models.FloatField()),
                ('launch_mass', models.FloatField()),
                ('thrust', models.FloatField()),
                ('burn_duration', models.FloatField()),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.organisation')),
                ('measures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.measure')),
            ],
        ),
        migrations.AlterField(
            model_name='astronaut',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.country'),
        ),
        migrations.CreateModel(
            name='VehicleStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('F', 'Fairing')], max_length=2)),
                ('dummy', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3)),
                ('launch_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.launchvehicle')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.stage')),
            ],
            options={
                'unique_together': {('launch_vehicle', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('astronauts', models.ManyToManyField(related_name='selections', through='space_missions.AstronautSelection', to='space_missions.Astronaut')),
                ('missions', models.ManyToManyField(to='space_missions.Mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='astronauts',
            field=models.ManyToManyField(blank=True, related_name='missions', through='space_missions.AstronautOccupation', to='space_missions.Astronaut'),
        ),
        migrations.AddField(
            model_name='mission',
            name='launch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space_missions.launch'),
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.organisation'),
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='measures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.measure'),
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='stages',
            field=models.ManyToManyField(blank=True, through='space_missions.VehicleStage', to='space_missions.Stage'),
        ),
        migrations.AddField(
            model_name='launch',
            name='launch_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.launchvehicle'),
        ),
        migrations.AddField(
            model_name='launch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_missions.organisation'),
        ),
        migrations.AddField(
            model_name='astronautselection',
            name='astronaut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.astronaut'),
        ),
        migrations.AddField(
            model_name='astronautselection',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.selection'),
        ),
        migrations.AddField(
            model_name='astronautoccupation',
            name='astronaut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.astronaut'),
        ),
        migrations.AddField(
            model_name='astronautoccupation',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_missions.mission'),
        ),
        migrations.AlterUniqueTogether(
            name='astronautselection',
            unique_together={('astronaut', 'selection')},
        ),
        migrations.AlterUniqueTogether(
            name='astronautoccupation',
            unique_together={('astronaut', 'mission')},
        ),
    ]
