# Generated by Django 3.2 on 2021-04-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0004_auto_20210426_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astronaut',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='astronautoccupation',
            options={'ordering': ['astronaut', 'mission']},
        ),
        migrations.AlterModelOptions(
            name='astronautselection',
            options={'ordering': ['astronaut', 'selection']},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='launch',
            options={'ordering': ['launch_id']},
        ),
        migrations.AlterModelOptions(
            name='launchvehicle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehiclestage',
            options={'ordering': ['launch_vehicle', 'stage']},
        ),
    ]
