# Generated by Django 3.1.7 on 2021-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0004_auto_20210422_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchvehicle',
            name='alias',
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='TO_thrust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='launch_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='max_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='min_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
