# Generated by Django 3.1.7 on 2021-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0005_auto_20210421_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchvehicle',
            name='measures',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='measures',
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='diameter',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='diameter',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='TO_thrust',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='launch_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='max_stage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='min_stage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='U_code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='english_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='t_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='t_stop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='burn_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='dry_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='launch_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='thrust',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
