# Generated by Django 3.1.7 on 2021-04-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0005_auto_20210422_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchvehicle',
            name='variant',
        ),
    ]
