# Generated by Django 3.1.7 on 2021-04-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0006_remove_launchvehicle_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclestage',
            unique_together={('launch_vehicle', 'stage', 'stage_number', 'dummy')},
        ),
    ]
