# Generated by Django 3.1.7 on 2021-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0007_remove_organisation_u_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Americas', 'Americas'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica')], default='Americas', max_length=10),
        ),
    ]
