# Generated by Django 3.1.2 on 2021-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0008_auto_20210423_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronautoccupation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='astronautselection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclestage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
