# Generated by Django 3.2 on 2021-04-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0008_auto_20210423_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
