# Generated by Django 3.2 on 2021-04-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0009_alter_country_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronaut',
            old_name='year_of_birth',
            new_name='birth_year',
        ),
    ]
