# Generated by Django 3.1.2 on 2021-04-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0009_auto_20210424_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
