# Generated by Django 3.2 on 2021-04-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0010_auto_20210421_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engine',
            unique_together={('name', 'manufacturer')},
        ),
    ]
