# Generated by Django 3.2 on 2021-04-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_missions', '0011_alter_engine_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
